name: Push image to dockerhub
on:
  push:
    branches: [main]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Produce image tag
        id: tag
        run: |
          repo="${{ github.repository }}"
          tag="${repo/${{ github.repository_owner }}/grascm}"
          echo $tag
          echo "::set-output name=res::$tag"
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: ${{ steps.tag.outputs.res }}
